version: '3.5'
services:

    db:
        image: mariadb:10.5
        user: mysql
        volumes:
            - ./docker/dbdata:/var/lib/mysql:cached
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "thisissecretpass"
            MYSQL_USER: "appuser"
            MYSQL_PASSWORD: "usersecretpass"
            MYSQL_DATABASE: "app"

    phpfpm:
        build:
            context: './'
            dockerfile: './docker/php-fpm/Dockerfile'
        shm_size: 256M
        working_dir: /var/www
        depends_on:
            - db
        volumes:
            - './app:/var/www:cached'
        environment:
            MYSQL_ROOT_PASSWORD: "thisissecretpass"
            MYSQL_USER: "appuser"
            MYSQL_PASSWORD: "usersecretpass"
            MYSQL_DATABASE: "app"
    
    nginx:
        image: nginx:1.19-alpine
        working_dir: /var/www/public
        ports:
            - "8080:80"
        depends_on:
            - phpfpm
        volumes:
            - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached'
            - './docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:cached'
            - './app/public:/var/www/public:cached'
